version: '3.8'
services:
  web:
    build: ./my-app
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
