version: '3.8'
services:
  web:
    build: ./next-vite-react
    ports:
      - "3000:3000"
    volumes:
      - ./next-vite-react:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
