version: '3.8'
services:
  web:
    build: ./next-vite-react
    ports:
      - "3000:3000"
    volumes:
      - ./next-vite-react:/app
      # - /next-vite-react/node_modules
      # - /next-vite-react/.next
    environment:
      - NODE_ENV=development
