FROM node:22-alpine

# RUN echo "Hello World"
# RUN ls
WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies
RUN npm install

RUN npm i -g serve

# Copy all other source code files
COPY . .

# Build the Next.js application
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Command to run the application
CMD [ "serve", "-s", "dist" ]